[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

# Ensure /api/* routes are not redirected to index.html
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirect all other routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200